# Generated by Django 2.2.4 on 2020-03-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200310_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Module')),
                ('professor', models.ManyToManyField(to='rating.Professor')),
            ],
            options={
                'unique_together': {('module', 'semester', 'year')},
            },
        ),
    ]
