# Generated by Django 2.2.4 on 2020-03-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_module_moduleinstance_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.ModuleInstance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.User')),
            ],
        ),
    ]
