# Generated by Django 2.2.4 on 2020-03-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_ratingrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='professor',
            new_name='professors',
        ),
    ]
