# Generated by Django 2.2.4 on 2020-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20200310_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingrecord',
            old_name='rate',
            new_name='rating',
        ),
    ]
