# Generated by Django 2.2.4 on 2020-03-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20200311_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='code',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='ratingrecord',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor', to_field='code'),
        ),
    ]
