# Generated by Django 2.2.4 on 2020-03-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_auto_20200311_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingrecord',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor'),
        ),
    ]
